### ISSUE TITLE
Evaluations dans la dernière mise à jour

### ISSUE THREAD

**Issue by sigalou** [dathosim/Pronote2Homeassistant#37]
Hello @dathosim  et bravo pour ce boulot, magnifique !

Ma fille est en évaluations et non en notes.
J'ai vu que tu avais publié une mise à jour du script et j'ai bien les évaluations dans le json.
Par contre quand tu as publié sur le dépôt, tu n'as pas ajouté le rest qui génère le sensor dans configuration.yaml
Sur la carte yaml, c'est bon, c'est prévu ensuite quand le sensor sera généré.

Tu as visiblement terminé le développement puisque on voit une copie d'écran sur le changelog.

Tu peux pousser les derniers fichiers ?
A ta dispo pour tester quoi que ce soit.

Merci, au plaisir

**Comment by Alpin38** [comment]
```
 - platform: rest
    name: pronote_eval_zoe
    scan_interval: 10
    json_attributes:
      - evaluation
    value_template: >
        {% if value_json.evaluation.0 is defined %}
            {{ value_json.evaluation.0.cours }} : {{ value_json.evaluation.0.evaluation_sur }} 
        {% else %}
            None
        {% endif %}
    resource: http://192.168.31.3:8123/local/pronote_zoe.json
```

**Comment by guillaume042** [comment]
Hello,
Question à propos de cela. 
J'utilise le script pour deux enfants. 
1 avec des notes
1 avec des évaluations.

Les notes cela passe sans soucis. 
Les evaluations cela plante .
Il y a un parametre à mettre dans config.ini pour passer en eval ?


```
Traceback (most recent call last):
  File "/config/python_scripts/pronote.py", line 162, in <module>
    grades = client.current_period.grades
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pronotepy/dataClasses.py", line 529, in grades
    grades = response["donneesSec"]["donnees"]["listeDevoirs"]["V"]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'listeDevoirs'
```

Merci
